import "styles/globals.css";
import Grid from "@mui/material/Grid";
import RootLayout from "app/layout";
import { TITLE } from "constants/texts";
import React from "react";
import Carousel from "components/Carousel";

export const metadata = {
  title: TITLE,
  description: "Generated by Next.js",
};

export default function Page() {
  return (
    <RootLayout>
      <Grid container item justifyContent="center">
        <Carousel />
      </Grid>
      <Grid container item justifyContent="center">
        Categories
        {/*{categories !== null ? <Categories list={categories} /> : null}*/}
      </Grid>
      <Grid
        container
        item
        textAlign="center"
        justifyContent="center"
        paddingTop={4}
      >
        <h2>Товары</h2>
      </Grid>
      <Grid container item justifyContent="center">
        Products
        {/*<Products products={products} errorResp={error} />*/}
      </Grid>
    </RootLayout>
  );
}
